// backend/controllers/historyController.js
//
// Handles history for both things QR Genie tracks:
//   - QRCode  : codes the user has generated and chosen to save
//   - Scan    : codes the user has scanned with the scanner page
//
// Assumes:
//   - authMiddleware.js runs before every route here and sets req.user.id
//   - models/QRCode.js  exports a Mongoose model with fields:
//       userId, type, content, foregroundColor, backgroundColor,
//       qrStyle, logo, createdAt
//   - models/Scan.js    exports a Mongoose model with fields:
//       qrId, userId, content, type, scannedAt, device
//     (content/type added so a scan can be saved even when it wasn't
//     generated by QR Genie first — see saveScan below)

const QRCode = require('../models/QRCode');
const Scan = require('../models/Scan');

const MAX_PAGE_SIZE = 50;

// Clamp ?limit and ?page query params to sane numbers
function parsePaging(query) {
  const limit = Math.min(parseInt(query.limit, 10) || 20, MAX_PAGE_SIZE);
  const page = Math.max(parseInt(query.page, 10) || 1, 1);
  return { limit, skip: (page - 1) * limit, page };
}

/* ------------------------------------------------------------------ */
/*  QR code history — codes the user generated and saved              */
/* ------------------------------------------------------------------ */

// GET /api/history/qrcodes
// List the signed-in user's saved QR codes, newest first.
exports.getQRHistory = async (req, res) => {
  try {
    const { limit, skip, page } = parsePaging(req.query);

    const [items, total] = await Promise.all([
      QRCode.find({ userId: req.user.id })
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit),
      QRCode.countDocuments({ userId: req.user.id })
    ]);

    res.json({
      items,
      page,
      limit,
      total,
      hasMore: skip + items.length < total
    });
  } catch (err) {
    console.error('getQRHistory error:', err);
    res.status(500).json({ message: 'Could not load your QR history.' });
  }
};

// DELETE /api/history/qrcodes/:id
// Remove one saved QR code. Only the owner can delete it.
exports.deleteQRCode = async (req, res) => {
  try {
    const qr = await QRCode.findOneAndDelete({
      _id: req.params.id,
      userId: req.user.id
    });

    if (!qr) {
      return res.status(404).json({ message: 'QR code not found.' });
    }

    res.json({ message: 'QR code deleted.', id: req.params.id });
  } catch (err) {
    console.error('deleteQRCode error:', err);
    res.status(500).json({ message: 'Could not delete that QR code.' });
  }
};

// DELETE /api/history/qrcodes
// Clear all saved QR codes for the signed-in user.
exports.clearQRHistory = async (req, res) => {
  try {
    const result = await QRCode.deleteMany({ userId: req.user.id });
    res.json({ message: 'QR history cleared.', deletedCount: result.deletedCount });
  } catch (err) {
    console.error('clearQRHistory error:', err);
    res.status(500).json({ message: 'Could not clear your QR history.' });
  }
};

/* ------------------------------------------------------------------ */
/*  Scan history — codes the user scanned with scanner.html            */
/* ------------------------------------------------------------------ */

// GET /api/history/scans
// List the signed-in user's scan history, newest first.
exports.getScanHistory = async (req, res) => {
  try {
    const { limit, skip, page } = parsePaging(req.query);

    const [items, total] = await Promise.all([
      Scan.find({ userId: req.user.id })
        .sort({ scannedAt: -1 })
        .skip(skip)
        .limit(limit),
      Scan.countDocuments({ userId: req.user.id })
    ]);

    res.json({
      items,
      page,
      limit,
      total,
      hasMore: skip + items.length < total
    });
  } catch (err) {
    console.error('getScanHistory error:', err);
    res.status(500).json({ message: 'Could not load your scan history.' });
  }
};

// POST /api/history/scans
// Save a scan. This is what scanner.html calls right after a decode.
// `qrId` is optional — a scanned code doesn't have to be one QR Genie made.
exports.saveScan = async (req, res) => {
  try {
    const { content, type, scannedAt, device, qrId } = req.body;

    if (!content || typeof content !== 'string' || !content.trim()) {
      return res.status(400).json({ message: 'Scan content is required.' });
    }

    const scan = await Scan.create({
      userId: req.user.id,
      qrId: qrId || undefined,
      content: content.trim(),
      type: type || 'Text',
      device: device || req.headers['user-agent'] || 'unknown',
      scannedAt: scannedAt ? new Date(scannedAt) : new Date()
    });

    res.status(201).json({ message: 'Scan saved.', scan });
  } catch (err) {
    console.error('saveScan error:', err);
    res.status(500).json({ message: 'Could not save that scan.' });
  }
};

// DELETE /api/history/scans/:id
// Remove one scan. Only the owner can delete it.
exports.deleteScan = async (req, res) => {
  try {
    const scan = await Scan.findOneAndDelete({
      _id: req.params.id,
      userId: req.user.id
    });

    if (!scan) {
      return res.status(404).json({ message: 'Scan not found.' });
    }

    res.json({ message: 'Scan deleted.', id: req.params.id });
  } catch (err) {
    console.error('deleteScan error:', err);
    res.status(500).json({ message: 'Could not delete that scan.' });
  }
};

// DELETE /api/history/scans
// Clear all scan history for the signed-in user.
exports.clearScanHistory = async (req, res) => {
  try {
    const result = await Scan.deleteMany({ userId: req.user.id });
    res.json({ message: 'Scan history cleared.', deletedCount: result.deletedCount });
  } catch (err) {
    console.error('clearScanHistory error:', err);
    res.status(500).json({ message: 'Could not clear your scan history.' });
  }
};